spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: easydonatenewsletter@gmail.com
    password: farahchouikh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  main:
    allow-bean-definition-overriding: true

